sudo: required
services:
  - docker

before_install:
  - docker build -t haomingzhang/docker-react -f Dockerfile.dev .

script:
  - docker run haomingzhang/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react-hm"
  env: "DockerReactHm-env"
  bucket_name: "elasticbeanstalk-us-west-1-732101137565"
  bucket_path: "docker-react-hm"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"